### ISSUE TITLE
unmanaged jars are ignored and cannot be used as dependencies

### ISSUE THREAD

**Issue by p-pavel** [doolse/sbt-osgi-felix#3]
OsgiTasks.createInstructionsTask uses update.value to generate list of dependencies, but update.value does not return unmanaged jars

**Comment by doolse** [comment]
Thanks @p-pavel , I've fixed it so that unmanaged jars are added to the top of processing faking up module and artifacts in the following way: 

``` scala
("unmanaged"` % f.getName % "1.0", Artifact(f.getName, "jar", "jar"), f)
```

But please note that it is not ideal to use unmanaged jars if they aren't already OSGi bundles as you won't benefit from the ordering of processing the jars as you get with proper maven dependencies.

**Comment by sjmarotta** [comment]
Thanks for addressing this. I have at least one unmanaged jar in my project and I'm getting a "Failed to find package..." error. How do I ensure that the unmanaged jar gets turned into an OSGi bundle?
